### ISSUE TITLE
Loggerを使う

### ISSUE THREAD

**Issue by danhper** [ohr486/tokyoex_handson_demo#2]
`IO.puts`を使ってるのはわかりやすくするためだと思いますが、せっかくなので、
https://github.com/ohr486/tokyoex_handson_demo/blob/master/web/crawler/engine.ex
で`Logger`を使って軽く使い方を紹介するのはどうでしょうか？

**Comment by ohr486** [comment]
ご提案ありがとうございます。
そうですね、Loggerの使い方紹介を追加したいと思います。
👍

**Comment by ohr486** [comment]
[ログの出力](https://github.com/ohr486/tokyoex_handson_demo/wiki/%E3%83%AD%E3%82%B0%E3%81%AE%E5%87%BA%E5%8A%9B) のページを追加しました
